#pragma once

#include "/Engine/Public/Platform.ush"

StructuredBuffer<float> InVolumetricLightmapMLPBuffer;
RWTexture3D<float4> OutVolumetricLightmapMLPTexture;
int3 Dimensions;

#define MAX_DIM 64
#define INPUT_DIM 3
#define OUTPUT_DIM 3

#define MIDDLE_LAYER_COUNT 5

#define SIREN_W0 30.0

float3 MlpForward(float3 InPos, StructuredBuffer<float> Weights)
{
	uint Offset = 0;

	float LayerIn[MAX_DIM];

	{
		int InDim = INPUT_DIM;   // 3
		int OutDim = MAX_DIM;    // 64
		uint BiasOffsetBase = Offset + (OutDim * InDim);
        
        	for (int o = 0; o < OutDim; o++)
        	{
        		float Sum = Weights[BiasOffsetBase + o];
        
        		uint WIdx = Offset + (o * InDim);
                    
        		Sum += InPos.x * Weights[WIdx + 0];
        		Sum += InPos.y * Weights[WIdx + 1];
        		Sum += InPos.z * Weights[WIdx + 2];
        
        		// Activation Func
        		// LayerIn[o] = max(0.0f, Sum); // ReLU
        		LayerIn[o] = sin(Sum * SIREN_W0); // SIREN
        	}
		Offset += (OutDim * InDim) + OutDim;
	}

	{
		float TempOut[MAX_DIM];
		for (int L = 0; L < MIDDLE_LAYER_COUNT; L++)
        	{
        		int Dim = MAX_DIM; // 64
        		uint BiasOffsetBase = Offset + (Dim * Dim);
        
        		for (int o = 0; o < Dim; o++)
        		{
        			float Sum = Weights[BiasOffsetBase + o];
                    
        			uint WStartIdx = Offset + (o * Dim);
        
        			for (int i = 0; i < Dim; i++)
        			{
        				Sum += LayerIn[i] * Weights[WStartIdx + i];
        			}
        
        			// Activation Func
        			// TempOut[o] = max(0.0f, Sum); // ReLU
        			TempOut[o] = sin(Sum * SIREN_W0); // SIREN
        		}
        
        		for (int k = 0; k < Dim; k++)
        		{
        			LayerIn[k] = TempOut[k];
        		}
        
        		Offset += (Dim * Dim) + Dim;
        	}
	}
	
	float3 Result;

	{
		int InDim = MAX_DIM;     // 64
		int OutDim = OUTPUT_DIM; // 3
        
		uint BiasOffsetBase = Offset + (OutDim * InDim);

		for (int o = 0; o < OutDim; o++)
		{
			float Sum = Weights[BiasOffsetBase + o];
			uint WStartIdx = Offset + (o * InDim);

			for (int i = 0; i < InDim; i++)
			{
				Sum += LayerIn[i] * Weights[WStartIdx + i];
			}

			Result[o] = Sum; 
		}
		
	}
	return Result;
}

[numthreads(8, 8, 8)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	if (any(DispatchThreadId >= Dimensions))
		return;
	float3 Pos = float3(DispatchThreadId.x * 1.0f / (Dimensions.x - 1), DispatchThreadId.y * 1.0f / (Dimensions.y - 1), DispatchThreadId.z * 1.0f / (Dimensions.z - 1));
	float3 Ambient = MlpForward(Pos, InVolumetricLightmapMLPBuffer);
	OutVolumetricLightmapMLPTexture[DispatchThreadId] = float4(Ambient, 1.0f);
}